# Generated by Django 3.1.1 on 2021-02-05 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation_site', '0004_auto_20210205_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='organization',
        ),
        migrations.AddField(
            model_name='donation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 10, 24, 32, 209457, tzinfo=utc)),
        ),
    ]
